/**
 * recovery.types.ts
 *
 * TypeScript types for recovery BullMQ jobs.
 *
 * WHY TYPED JOBS?
 * BullMQ stores job data as JSON. Without types, workers would receive `any`
 * and have no guarantee about what fields exist. Typed job data means:
 *   1. Workers get compile-time errors if they access a field that doesn't exist.
 *   2. The queue producer (webhook route) gets errors if it omits required fields.
 *   3. Future devs can understand what data flows through the queue by reading this file.
 *
 * JOB TYPE OVERVIEW:
 *   RetryPaymentJobData    → Worker calls gateway API to attempt payment retry
 *   SendEmailJobData       → Worker sends recovery email via Resend
 *   SendWhatsAppJobData    → Worker sends WhatsApp message via Interakt/MSG91
 *   SendSmsJobData         → Worker sends SMS via MSG91 DLT
 *
 * WHY SEPARATE TYPES PER CHANNEL?
 * Each channel has different required data. Email needs merchant branding.
 * WhatsApp needs the approved template name. SMS needs DLT template ID.
 * A single union type with all optional fields would be error-prone.
 * Union discrimination with a 'type' field gives exhaustive type checking.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Shared base data included in every recovery job
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Context that every recovery job needs, regardless of job type.
 *
 * WHY INCLUDE CUSTOMER DATA DIRECTLY IN THE JOB?
 * Workers run asynchronously, potentially minutes or hours after the payment failed.
 * Rather than querying the DB for customer info inside each worker, we embed the
 * essential data in the job payload at enqueue time.
 * WHY: Reduces DB queries on hot paths. Worker processes faster. Easier to debug
 * (job payload contains everything needed to understand what it was trying to do).
 */
interface RecoveryJobBase {
  // Core identifiers
  failedPaymentId: string;   // UUID of the failed_payments row
  merchantId: string;        // UUID of the merchant
  recoveryJobDbId: string;   // UUID of the recovery_jobs audit row (for status updates)

  // Payment context (cached from failed_payments at job creation time)
  amountPaise: number;       // How much was the failed payment (in PAISE)
  currency: string;          // 'INR', 'USD', etc.
  customerEmail?: string;
  customerPhone?: string;
  customerName?: string;

  // Which gateway and payment
  gatewayName: 'razorpay' | 'stripe' | 'cashfree' | 'payu';
  gatewayPaymentId: string;
  gatewaySubscriptionId?: string;

  /**
   * Which step in the recovery sequence this job represents.
   * Step 1: Gentle reminder (Day 0-1)
   * Step 2: Urgent follow-up (Day 3-4)
   * Step 3: Final attempt + pause offer (Day 6-7)
   */
  stepNumber: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// Job-specific data types
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Data for a payment retry job.
 *
 * The worker uses gatewayPaymentId + gatewayName to call the gateway API
 * and attempt to collect the payment again.
 *
 * WHY INCLUDE attemptNumber?
 * Workers need to know if this is attempt 1, 2, or 3 to:
 *   a) Enforce the NPCI 4-attempt rule for UPI AutoPay
 *   b) Decide what to do on failure (retry again or escalate to email sequence)
 */
export interface RetryPaymentJobData extends RecoveryJobBase {
  type: 'retry_payment';
  attemptNumber: number;       // 1-indexed (1 = first retry after original failure)
  paymentMethodType: string;   // 'upi_autopay', 'credit_card', etc.
  isRecoverable: boolean;      // Should always be true for retry jobs; checked defensively
}

/**
 * Data for an email outreach job.
 *
 * The worker renders the appropriate email template and sends via Resend.
 * WHY INCLUDE merchantBranding: Avoids a DB query inside the worker.
 * The merchant's "from" name, reply-to, and brand color are needed to render
 * the email — embedding them at job creation means the worker stays stateless.
 */
export interface SendEmailJobData extends RecoveryJobBase {
  type: 'send_email';

  // Merchant branding (fetched from merchant_brand_settings at job creation time)
  merchantFromName: string;    // e.g., "FynBack Recovery" or merchant's custom name
  merchantFromEmail: string;   // e.g., "recovery@merchant.com"
  merchantReplyTo: string;
  merchantBrandColor: string;  // Hex color for email header/button

  // Payment link (pre-generated by the worker or stored after mandate cancellation)
  paymentLink?: string;

  /**
   * Whether to include the "Pause your subscription for 1 month" offer.
   * WHY: This offer recovers 25-30% of users who would otherwise churn permanently.
   * It's only shown on the final step (stepNumber === 3) to avoid training customers
   * to ignore emails waiting for the pause offer.
   */
  includePauseOffer: boolean;
}

/**
 * Data for a WhatsApp outreach job.
 *
 * WHY WHATSAPP IS CRITICAL FOR INDIA:
 * WhatsApp has 550M+ users in India with 80-95% open rates vs 10-20% for email.
 * For B2C merchants (EdTech, D2C), WhatsApp is the primary recovery channel.
 *
 * WHY TEMPLATE-BASED:
 * WhatsApp Business API requires pre-approved message templates for proactive
 * (business-initiated) messages. We can't send free-form text — must use templates
 * that were approved by Meta. The template name identifies which template to use.
 */
export interface SendWhatsAppJobData extends RecoveryJobBase {
  type: 'send_whatsapp';

  /**
   * Pre-approved Meta/WhatsApp Business template name.
   * Example: 'payment_failed_reminder_v1', 'payment_failed_urgent_v2'
   * WHY: WhatsApp will reject unrecognized template names with an error.
   * Template names are set up in the merchant's Interakt/MSG91 account.
   */
  templateName: string;

  /**
   * Variables to inject into the template (ordered list).
   * WhatsApp templates use {{1}}, {{2}}, etc. for dynamic content.
   * Example: ['John', '₹2,400', 'App Name', 'https://pay.link/abc']
   */
  templateVariables: string[];

  paymentLink?: string;
}

/**
 * Data for an SMS outreach job (fallback when WhatsApp is not enabled).
 *
 * WHY SMS LAST (not second)?
 * In India, SMS has ~30-50% open rates but requires DLT (Distributed Ledger Technology)
 * registration under TRAI rules. It's the most regulated channel.
 * WhatsApp (80-95% open rate, less regulatory friction) is always preferred.
 * SMS is the fallback for merchants without WhatsApp enabled.
 *
 * WHY DLT TEMPLATE ID?
 * TRAI (India's telecom regulator) mandates that all promotional/transactional SMS
 * must use pre-registered templates. The dltTemplateId identifies the approved template.
 * Without it, Indian telecom operators will block the SMS at the carrier level.
 */
export interface SendSmsJobData extends RecoveryJobBase {
  type: 'send_sms';

  /**
   * TRAI DLT registered template ID.
   * This is a numeric ID assigned when the template is registered with TRAI.
   * Without a valid DLT template ID, Indian carriers will not deliver the SMS.
   */
  dltTemplateId: string;

  /** The SMS body text (must exactly match the DLT registered template, with variable substitution). */
  smsBody: string;

  paymentLink?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Union type used by the BullMQ worker
// ─────────────────────────────────────────────────────────────────────────────

/**
 * The discriminated union of all recovery job data types.
 *
 * WHY DISCRIMINATED UNION?
 * Workers receive this type and switch on the 'type' field.
 * TypeScript narrows the type in each branch, giving full type safety:
 *
 *   switch (job.data.type) {
 *     case 'retry_payment':
 *       // TypeScript knows job.data is RetryPaymentJobData here
 *       job.data.attemptNumber; // ✓ type-safe
 *     case 'send_email':
 *       // TypeScript knows job.data is SendEmailJobData here
 *       job.data.merchantFromName; // ✓ type-safe
 *   }
 */
export type RecoveryJobData =
  | RetryPaymentJobData
  | SendEmailJobData
  | SendWhatsAppJobData
  | SendSmsJobData;
